export {default as Header} from "./Header";
export {default as Footer} from "./Footer";
export {default as Navbar} from "./Navbar";
export {default as Quote} from "./Quote";
export {default as ScrollBig} from "./ScrollBig";
export {default as Service} from "./Sevices";
export {default as ScrollSmall} from "./SrollSmall";
export {default as WhyUs} from "./WhyUs";
export {default as Works} from "./Works";